### ISSUE TITLE
`adapters/coingecko.ts` implementation testing

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/oracle-adapters#15]
#### What would you like to be added:

Testing of `adapters/src/coingecko.ts` `AssetPrice[]` adapter. Since this endpoint is exposed? We can test it via the live endpoint?

**Comment by monstrobishi** [comment]
Can you elaborate on this? Do you mean always test via the live endpoint not using nock?

**Comment by fuxingloh** [comment]
Yeah, for adapters that don't have access control.

**Comment by fuxingloh** [comment]
Closed with #29
