### ISSUE TITLE
TimestampFilter: Timestamp must be valid and within a configurable range +- (Default: 3 weeks in the past, one hour into the future) from `Date.now()`

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/oracle-adapters#24]

**Comment by fuxingloh** [comment]
This will require a change in salmon-fetch to include a timestamp

**Comment by monstrobishi** [comment]
Check has been changed to 3 weeks as we want to always send price regardless of age (However 3 weeks is a good sanity check)

**Comment by fuxingloh** [comment]
Indicating `+/-` of 3 weeks, probably should not allow future date far into the seconds?

**Comment by monstrobishi** [comment]
Fair point, I would do one hour in the future as that conforms with the original oracles spec.

Will change title to three weeks back and one hour into the future.

**Comment by fuxingloh** [comment]
@joeldavidw to change #64
