### ISSUE TITLE
New Prevout provider that allows sending subsequent tx

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/oracle-adapters#68]
#### What would you like to be added:

Since we are doing an overhaul, it would be good to consider if we can implement a prevout provider that allows sending tx in sequence without waiting for the previous one to evaluate.

**Comment by fuxingloh** [comment]
/area salmon-wallet

How can we do it? 🤔

**Comment by monstrobishi** [comment]
Cache vout of previous tx, use it as prevout of next tx without waiting for consensus. Would either require some intermediate storage or whale to provide a view of the mempool.

**Comment by ivan-zynesis** [comment]
Sounds good `WhalePrevoutProvider.all().filter(prevout => !ExtendedProvider.cachedSpent().includes(prevout))`
